version: '3.4'

services:
  db:
    image: postgres:9.6-alpine
    container_name: nuxt-auth0-todo-app
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DEV_DB_NAME}
      - POSTGRES_USER=${DEV_DB_USER_NAME}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
