# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fb0499cca5ee7d6f8b71a4a29712f8ced14e96cccb4ef602c79f2e929cd26378495c40478d0605febda6b1baf65729060bbd425805342c949f21b07d35571ae

test:
  secret_key_base: 211cef2798ff27b3e30d8e0035f4e6daede040902baf29e40188e1779ee2e433f1e4072902ea36b5ece909231d5118c6754b5c058c639a4535c6d2fd579463f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
